<?php
    $configValue = Mage::getStoreConfig('elitrack/elitrack/elitrack_api_fld');

    $cust_enable=Mage::getStoreConfig('elitrack/elitrack/elitrack_custid_fld');

    $custid='';
    $total='';

     if($cust_enable=='1')
    {

		    if(Mage::getSingleton('customer/session')->isLoggedIn()) 
		    {
		      $customerData = Mage::getSingleton('customer/session')->getCustomer();
		     // print_r($customerData);
		      if(!empty($customerData))
		      {
		      	$custid= md5($customerData->getId());
		      }
		      
		 	}		 	
	}
	if($configValue!='')
	{
		$cart = Mage::getModel('checkout/cart')->getQuote();
 			$prolist=''; 	
 			$i=1;
 			$count=count($cart->getAllVisibleItems());
			foreach ($cart->getAllVisibleItems() as $item)
			{
				
				$productName = $item->getName();
				$proId = $item->getProductId();
				$productPrice = $item->getPrice();
				$qty = $item->getQty();
	   		 $proprice=$qty*$productPrice;
				$total=$total+$proprice;

								

						if($i==$count)
						{
						$prolist.=$proId.':'.$proprice.':'.$productPrice;
						}		
						else
						{
					$prolist.=$proId.':'.$proprice.':'.$productPrice.';';
						}
				
				
		
				$i++;
			}
			$str='<script type="text/javascript">
		(function() {
		var script = document.createElement("script");
		script.type = "text\/javascript";
		script.charset = "UTF-8";
		script.async = "async";
		script.defer = "defer";
		script.src = ("https:" == document.location.protocol ? "https": "http")+"://tck.elitrack.com/tag?page=cart&aid='.$configValue.'&cid='.$custid.'&products='.$prolist.'&totalPrice='.$total.'";document.getElementsByTagName("head")[0].appendChild(script);
		})();
		</script>';
		echo $str;

	}

?>