<?php
    $configValue = Mage::getStoreConfig('elitrack/elitrack/elitrack_api_fld');
    $cust_enable=Mage::getStoreConfig('elitrack/elitrack/elitrack_custid_fld');

    $custid='';

     if($cust_enable=='1')
    {

    if(Mage::getSingleton('customer/session')->isLoggedIn()) 
    {
      $customerData = Mage::getSingleton('customer/session')->getCustomer();
      $custid= md5($customerData->getId());
 	}
 }
 if($configValue!='')
 {
 	$proid=Mage::registry('current_product')->getId();    

$str='<script type="text/javascript">
(function() {
var script = document.createElement("script");
script.type = "text\/javascript";
script.charset = "UTF-8";
script.async = "async";
script.defer = "defer";
script.src = ("https:" == document.location.protocol ? "https": "http")+"://tck.elitrack.com/tag?page=product&aid='.$configValue.'&cid='.$custid.'&prodId='.$proid.'";document.getElementsByTagName("head")[0].appendChild(script);
})();
</script>';
echo $str;


 }

 	
?>